name: build_and_unit_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, edited, ready_for_review ]
  workflow_dispatch:

jobs:

  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: go/src/github.com/apache/cloudberry-backup

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set Environment
      run: |
        echo "GOPATH=${GITHUB_WORKSPACE}/go" >> $GITHUB_ENV
        echo "${GITHUB_WORKSPACE}/go/bin" >> $GITHUB_PATH

    - name: Dependencies
      run: |
        cd ${GOPATH}/src/github.com/apache/cloudberry-backup
        make depend

    - name: Build
      run: |
        cd ${GOPATH}/src/github.com/apache/cloudberry-backup
        make build

    - name: Unit Test
      run: |
        cd ${GOPATH}/src/github.com/apache/cloudberry-backup
        make unit_all_gpdb_versions
